package services_certificatepdf

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"example.com/m/internal/models"
	"github.com/jung-kurt/gofpdf"
)

type CertificatePDFService struct {
	outputDir string
}

func NewCertificatePDFService(outputDir string) *CertificatePDFService {
	return &CertificatePDFService{
		outputDir: outputDir,
	}
}

func (s *CertificatePDFService) Generate(issue *models.CertificateIssue) (string, error) {
	if err := os.MkdirAll(s.outputDir, os.ModePerm); err != nil {
		return "", err
	}

	fileName := fmt.Sprintf("certificate_%s.pdf", issue.CertificateNumber)
	filePath := filepath.Join(s.outputDir, fileName)

	pdf := gofpdf.New("L", "mm", "A4", "")
	pdf.AddPage()

	// Border
	pdf.SetLineWidth(1.5)
	pdf.Rect(10, 10, 277, 190, "D")

	pdf.SetLineWidth(0.4)
	pdf.Rect(16, 16, 265, 178, "D")

	// Title
	pdf.SetFont("Arial", "B", 30)
	pdf.CellFormat(0, 30, "Certificate of Completion", "", 1, "C", false, 0, "")

	pdf.Ln(8)

	pdf.SetFont("Arial", "", 14)
	pdf.CellFormat(0, 10, "This certificate is proudly presented to", "", 1, "C", false, 0, "")

	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 26)
	pdf.CellFormat(0, 14, issue.User.FullName, "", 1, "C", false, 0, "")

	pdf.Ln(5)

	pdf.SetFont("Arial", "", 14)
	pdf.CellFormat(0, 10, "for successfully completing the course", "", 1, "C", false, 0, "")

	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 22)
	pdf.CellFormat(0, 14, issue.Certification.Course.CourseTitle, "", 1, "C", false, 0, "")

	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(0, 8, fmt.Sprintf("Certification: %s", issue.Certification.CertificationName), "", 1, "C", false, 0, "")

	pdf.CellFormat(0, 8, fmt.Sprintf("Certificate No: %s", issue.CertificateNumber), "", 1, "C", false, 0, "")

	pdf.CellFormat(0, 8, fmt.Sprintf("Issued On: %s", issue.IssuedOn.Format("02 Jan 2006")), "", 1, "C", false, 0, "")

	pdf.CellFormat(0, 8, fmt.Sprintf("Valid Until: %s", issue.ExpiryDate.Format("02 Jan 2006")), "", 1, "C", false, 0, "")

	pdf.Ln(15)

	pdf.SetFont("Arial", "I", 11)
	pdf.CellFormat(0, 8, fmt.Sprintf("Generated by LMS on %s", time.Now().Format("02 Jan 2006 15:04")), "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(filePath); err != nil {
		return "", err
	}

	return filePath, nil
}
